from __future__ import annotations
import hashlib,json
from pathlib import Path
import unittest
from src.polyphonic import harmonic_censoring_h27_activation_capable_production_materializer_dormant as m
from src.polyphonic import harmonic_censoring_h27_future_bridge_activation_artifact_dormant as a
from src.polyphonic import harmonic_censoring_h27_future_bridge_activation_artifact_publication_dormant as p
from src.polyphonic import harmonic_censoring_h27_future_bridge_activation_artifact_real_publication_dormant as r
from src.polyphonic import harmonic_censoring_h27_future_bridge_dormant as b
from src.polyphonic import harmonic_censoring_h27_future_bridge_operational_activation_connection_dormant as g
from src.polyphonic import harmonic_censoring_h27_issuer_authority_claim_capability_dormant as q
from src.polyphonic import harmonic_censoring_h27_one_shot_execution_composition_dormant as c
from tests.test_harmonic_censoring_h27_real_publication_authority_instance_artifact_constructor_execution_gate_contract_identity_binding import hundred_sixteen
ROOT=Path(__file__).resolve().parents[1];C=ROOT/'configs/harmonic_censoring_h27_constructor_execution_gate_control_bundle_creation_contract.json';S=ROOT/'configs/harmonic_censoring_h27_constructor_execution_gate_control_bundle_creation_contract_external_seal.json'
def blob(x):return hashlib.sha1(b'blob '+str(len(x)).encode()+b'\0'+x).hexdigest()
def chk(t,x):
 raw=(ROOT/x['path']).read_bytes();t.assertEqual((x['git_blob_sha1'],x['size_bytes'],x['raw_sha256']),(blob(raw),len(raw),hashlib.sha256(raw).hexdigest()));return raw
class TestControlBundleCreationContract(unittest.TestCase):
 @classmethod
 def setUpClass(cls):cls.cr=C.read_bytes();cls.sr=S.read_bytes();cls.c=json.loads(cls.cr);cls.s=json.loads(cls.sr)
 def test_exact_seal_manifest_and_120_predecessors(self):
  for raw in (self.cr,self.sr):self.assertNotIn(b'\r',raw);self.assertFalse(raw.startswith(b'\xef\xbb\xbf'));self.assertTrue(raw.endswith(b'\n'))
  chk(self,self.s['contract']);roots=self.c['reviewed_and_sealed_gate_contract_chain'];gate=json.loads((ROOT/roots[0]['path']).read_bytes());entries=[*roots,*hundred_sixteen(gate)];self.assertEqual((len(entries),len({x['path'] for x in entries})),(120,120));[chk(self,x) for x in entries];manifest=self.c['closed_six_file_manifest'];self.assertEqual((len(manifest),len({x['path'] for x in manifest})),(6,6));[chk(self,x) for x in manifest]
 def test_exact_paths_order_rules_state_and_edges(self):
  d=self.c['bundle_definition'];self.assertEqual(list(d),['administrative_root','control_parent','final_bundle_root','staging_bundle_root','source_git_object_database','source_requires_exact_git_blob_lookup_only','source_checkout_file_reads_forbidden','relative_paths_preserved_exactly','immutable_after_publication']);self.assertEqual((d['administrative_root'],d['control_parent'],d['final_bundle_root'],d['staging_bundle_root'],d['source_git_object_database']),('/Users/amcarene/h27-admin','/Users/amcarene/h27-admin/control','/Users/amcarene/h27-admin/control/h27-constructor-execution-gate-v1','/Users/amcarene/h27-admin/control/.h27-constructor-execution-gate-v1.staging','/Users/amcarene/midi-worker/repository/.git'));self.assertTrue(all(v for k,v in d.items() if k not in ('administrative_root','control_parent','final_bundle_root','staging_bundle_root','source_git_object_database')))
  self.assertEqual(self.c['future_fail_closed_creation_order'],['rehash_all_one_hundred_twenty_predecessor_identities','verify_exact_git_object_database_path_and_no_symlink_escape','extract_each_of_six_blobs_by_exact_git_blob_sha1','verify_each_extracted_blob_size_and_sha256','verify_control_parent_realpath_is_exact_and_not_symlinked','probe_final_and_staging_bundle_absence_once','create_staging_bundle_exclusively','write_exact_six_files_with_preserved_relative_paths_and_no_overwrite','fsync_files_and_directories','rehash_staged_closed_manifest','rename_staging_to_final_atomically_without_overwrite','rehash_final_closed_manifest','mark_success_terminal'])
  rules=self.c['future_creation_rules'];self.assertEqual(list(rules),['exactly_six_files_and_no_extras','duplicate_or_noncanonical_relative_path_forbidden','absolute_or_parent_traversal_path_forbidden','source_blob_missing_or_mismatch_terminal_before_creation','existing_final_or_staging_path_terminal_before_creation','exclusive_creation_required','overwrite_forbidden','partial_publication_forbidden','success_terminal','post_first_filesystem_effect_failure_terminal','retry_after_first_filesystem_effect_forbidden','bundle_creation_requires_distinct_later_authority_artifact_and_external_review']);self.assertTrue(all(rules.values()));self.assertTrue(self.c['transitive_identity_source']['all_one_hundred_twenty_identities_must_be_rehashed_before_any_bundle_path_observation'])
  self.assertEqual([(x['path'],x['git_blob_sha1'],x['size_bytes'],x['raw_sha256']) for x in self.c['closed_six_file_manifest']],[('configs/harmonic_censoring_h27_real_publication_authority_instance_artifact_constructor_execution_gate_contract.json','1bdc95411520793c2f1ff0c08ef2245e569ef2a0',6387,'0134f4c459ac9d4e642da70dbcf257f34998db064e568ea0e039b58d5952f215'),('configs/harmonic_censoring_h27_real_publication_authority_instance_artifact_constructor_execution_gate_contract_external_seal.json','099703d92d9cfd761f5aa9065467fff1516d5a46',1673,'6cd9cc7f67c60ea71804fd01137ee2fddd1947c0fb0e56d3bc7d0db362054778'),('configs/harmonic_censoring_h27_real_publication_authority_instance_artifact_constructor_execution_authority_artifact.json','fedcf0f1c2be368ddf619e8f1715a55f499815c8',688,'dccc4afaf20390fe07226fbfd237c06b381b203d25f6f80908adc3753c985296'),('configs/harmonic_censoring_h27_real_publication_authority_instance_artifact_constructor_execution_authority_artifact_external_seal.json','4f3e49d29e5777b1ad5174b24870ac21f348ac78',1683,'5b2b985f694b1e360afc9aec84a6ba8329cf6bc7b4cfea106a67108ac550decc'),('configs/harmonic_censoring_h27_real_publication_authority_instance_artifact_constructor_execution_authority_artifact_identity_binding.json','fe89c67096bef9e41a0405a1e37a291be5fd1afa',2986,'8e9549db0821ed3f0334aab369abb18373bc5e2141d656b8e0c0e5ba6a65a9da'),('configs/harmonic_censoring_h27_real_publication_authority_instance_artifact_constructor_execution_authority_artifact_identity_binding_external_seal.json','3d79c43ee50ccc9b2e87c3c07d63a2061b18edbf',1431,'95892205cf7af0d84a5ec75b466467486eb50996d4040bdca7d25e4b9a58940c')])
  allowed={'control_bundle_creation_contract_exists'}
  for k,v in self.c['current_state'].items():self.assertIs(v,k in allowed,k)
  graph=self.c['dependency_graph'];self.assertTrue(graph['acyclic'] and graph['all_one_hundred_twenty_predecessor_identities_rehashed']);self.assertFalse(graph['self_hash_present'] or graph['historical_back_reference_present']);self.assertEqual((self.s['bound_identity_count'],self.s['bundle_file_count'],self.c['public_edges_closed']),(120,6,8));self.assertFalse(any(self.s[k] for k in ('administrative_control_bundle_exists','bundle_path_observed','filesystem_operation_authorized','persistent_registry_opened','identity_nonce_reserved','constructor_invoked_really','destination_observed','science_or_locked_test')))
  for e in (c.execute_h27_one_shot_composition,b.invoke_h27_future_bridge,g.activate_and_connect_h27_future_bridge,a.construct_h27_future_bridge_activation_artifact,p.simulate_h27_future_bridge_activation_artifact_publication,r.publish_h27_future_bridge_activation_artifact_real,q.issue_h27_materialization_authority_and_capability,m.materialize_h27_activation_capable_production_population):self.assertIs(type(e),type(().__getitem__))
 def test_no_backrefs(self):
  roots=self.c['reviewed_and_sealed_gate_contract_chain'];gate=json.loads((ROOT/roots[0]['path']).read_bytes())
  for x in [*roots,*hundred_sixteen(gate)]:raw=(ROOT/x['path']).read_bytes();self.assertNotIn(C.name.encode(),raw);self.assertNotIn(S.name.encode(),raw)
if __name__=='__main__':unittest.main()
